import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';
import '../providers/assistant_provider.dart';
import '../../../auth/presentation/pages/auth_providers.dart';

class AssistantPlanApprovePage extends ConsumerStatefulWidget {
  final String messageId;
  const AssistantPlanApprovePage({super.key, required this.messageId});

  @override
  ConsumerState<AssistantPlanApprovePage> createState() => _AssistantPlanApprovePageState();
}

class _AssistantPlanApprovePageState extends ConsumerState<AssistantPlanApprovePage> {
  double _sliderPosition = 0.0;
  final double _sliderWidth = 280.0;
  final double _thumbSize = 56.0;
  bool _isProcessing = false;

  @override
  Widget build(BuildContext context) {
    final state = ref.watch(assistantProvider);
    final msg = state.messages.firstWhere((m) => m.id == widget.messageId, orElse: () => null as dynamic);

    if (msg == null || msg.plan == null) {
      return Scaffold(
        appBar: AppBar(title: const Text('Authorize Plan')),
        body: const Center(child: Text('Loading plan metadata...')),
      );
    }

    final plan = msg.plan!;

    return Scaffold(
      appBar: AppBar(
        title: const Text('AI Plan Authorization'),
      ),
      body: Stack(
        children: [
          Padding(
            padding: const EdgeInsets.all(24.0),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.stretch,
              children: [
                Container(
                  padding: const EdgeInsets.all(16),
                  decoration: BoxDecoration(
                    color: Colors.orange.shade50,
                    borderRadius: BorderRadius.circular(12),
                    border: Border.all(color: Colors.orange.shade300),
                  ),
                  child: Row(
                    children: [
                      Icon(Icons.shield_outlined, color: Colors.orange.shade800, size: 36),
                      const SizedBox(width: 16),
                      const Expanded(
                        child: Column(
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            Text(
                              'AI Plan Execution Gate',
                              style: TextStyle(fontWeight: FontWeight.bold, fontSize: 15),
                            ),
                            SizedBox(height: 4),
                            Text(
                              'Please review the multi-step mutations generated by the AI model. Signatures will be released to the C2 bus.',
                              style: TextStyle(color: Colors.grey, fontSize: 12),
                            ),
                          ],
                        ),
                      ),
                    ],
                  ),
                ),
                const SizedBox(height: 24),
                const Text(
                  'MUTATION STEPS',
                  style: TextStyle(fontSize: 12, fontWeight: FontWeight.bold, color: Colors.grey, letterSpacing: 1.2),
                ),
                const SizedBox(height: 12),
                Expanded(
                  child: Card(
                    child: ListView.builder(
                      itemCount: plan.steps.length,
                      padding: const EdgeInsets.all(16),
                      itemBuilder: (context, index) {
                        final step = plan.steps[index];
                        return ListTile(
                          leading: CircleAvatar(
                            backgroundColor: Colors.grey.shade100,
                            child: Text('${index + 1}', style: const TextStyle(fontWeight: FontWeight.bold)),
                          ),
                          title: Text(step.description, style: const TextStyle(fontWeight: FontWeight.bold)),
                          subtitle: Text('${step.commandType} • ${step.riskLevel} Risk'),
                        );
                      },
                    ),
                  ),
                ),
                const SizedBox(height: 24),
                // Swipe Slider Track
                Center(
                  child: Container(
                    width: _sliderWidth,
                    height: _thumbSize,
                    decoration: BoxDecoration(
                      color: Colors.grey.shade100,
                      borderRadius: BorderRadius.circular(_thumbSize / 2),
                      border: Border.all(color: Colors.grey.shade300),
                    ),
                    child: Stack(
                      children: [
                        Center(
                          child: Text(
                            'SLIDE TO SIGN & EXECUTE',
                            style: TextStyle(
                              color: Colors.grey.shade600,
                              fontWeight: FontWeight.bold,
                              fontSize: 10,
                              letterSpacing: 1.5,
                            ),
                          ),
                        ),
                        Positioned(
                          left: _sliderPosition,
                          child: GestureDetector(
                            onHorizontalDragUpdate: _isProcessing ? null : (details) {
                              setState(() {
                                _sliderPosition += details.primaryDelta!;
                                if (_sliderPosition < 0) _sliderPosition = 0;
                                final maxPos = _sliderWidth - _thumbSize;
                                if (_sliderPosition > maxPos) _sliderPosition = maxPos;
                              });
                            },
                            onHorizontalDragEnd: _isProcessing ? null : (details) async {
                              final maxPos = _sliderWidth - _thumbSize;
                              if (_sliderPosition >= maxPos * 0.9) {
                                setState(() {
                                  _sliderPosition = maxPos;
                                });
                                await _signAndDispatch();
                              } else {
                                setState(() {
                                  _sliderPosition = 0.0;
                                });
                              }
                            },
                            child: Container(
                              width: _thumbSize,
                              height: _thumbSize,
                              decoration: const BoxDecoration(
                                shape: BoxShape.circle,
                                color: Colors.green,
                              ),
                              child: const Icon(Icons.arrow_forward, color: Colors.white),
                            ),
                          ),
                        ),
                      ],
                    ),
                  ),
                ),
                const SizedBox(height: 24),
              ],
            ),
          ),
          if (_isProcessing)
            const Container(
              color: Colors.black26,
              child: Center(child: CircularProgressIndicator()),
            ),
        ],
      ),
    );
  }

  Future<void> _signAndDispatch() async {
    setState(() => _isProcessing = true);
    try {
      final biometricService = ref.read(biometricServiceProvider);
      final assistantNotifier = ref.read(assistantProvider.notifier);

      final authenticated = await biometricService.authenticate(
        reason: 'Biometric verification is required to release the AI plan execution signature.',
      );

      if (!authenticated) {
        setState(() {
          _sliderPosition = 0.0;
          _isProcessing = false;
        });
        if (mounted) {
          ScaffoldMessenger.of(context).showSnackBar(
            const SnackBar(content: Text('Biometric verification failed.'), backgroundColor: Colors.red),
          );
        }
        return;
      }

      final success = await assistantNotifier.executePlan(widget.messageId);

      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text(success ? 'Plan signature verified. Execution initiated.' : 'Execution failed.'),
            backgroundColor: success ? Colors.green : Colors.red,
          ),
        );
        if (success) {
          context.pop();
        } else {
          setState(() {
            _sliderPosition = 0.0;
          });
        }
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('Error: $e'), backgroundColor: Colors.red),
        );
        setState(() {
          _sliderPosition = 0.0;
        });
      }
    } finally {
      if (mounted) setState(() => _isProcessing = false);
    }
  }
}
