apiVersion: v1
kind: ConfigMap
metadata:
  name: aegisos-configs
  namespace: aegisos-ops
data:
  nginx.conf: |
    user nginx;
    worker_processes auto;
    events { worker_connections 1024; }
    http {
        include mime.types;
        sendfile on;
        server {
            listen 80;
            location / {
                proxy_pass http://console-service:3000;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
            }
        }
    }

  litellm-config.yaml: |
    model_list:
      - model_name: smollm:135m
        litellm_params:
          model: ollama/smollm:135m
          api_base: http://ollama-service:11434
    litellm_settings:
      drop_params: true
      set_verbose: false

  otel-collector-config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
    processors:
      batch:
        timeout: 1s
    exporters:
      prometheus:
        endpoint: 0.0.0.0:8889
      otlp/jaeger:
        endpoint: jaeger-service:4317
        tls:
          insecure: true
    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlp/jaeger]
        metrics:
          receivers: [otlp]
          processors: [batch]
          exporters: [prometheus]

  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'otel-collector'
        static_configs:
          - targets: ['otel-collector-service:8889']
      - job_name: 'console-app'
        metrics_path: '/api/metrics'
        static_configs:
          - targets: ['console-service:3000']
