/**
 * MockReasoningProvider
 * 
 * Used for Tier 0 (Platform Determinism) benchmarks.
 * Provides deterministic, pre-recorded, or synthetic responses 
 * with configurable latency and token rates to isolate platform overhead.
 */

export interface MockProviderConfig {
  tokensPerSecond: number;
  fixedLatencyMs: number;
  failureProbability: number;
  hallucinationProbability: number;
  contextSize: number;
  preRecordedResponses?: Record<string, string>;
}

export class MockReasoningProvider {
  private config: MockProviderConfig;

  constructor(config: Partial<MockProviderConfig> = {}) {
    this.config = {
      tokensPerSecond: 50,
      fixedLatencyMs: 100,
      failureProbability: 0,
      hallucinationProbability: 0,
      contextSize: 4096,
      ...config
    };
  }

  async generateResponse(prompt: string): Promise<string> {
    if (Math.random() < this.config.failureProbability) {
      throw new Error("Mock Reasoning Provider simulated failure.");
    }

    // Simulate initial latency
    await this.delay(this.config.fixedLatencyMs);

    const response = this.getResponseForPrompt(prompt);
    
    // Simulate token streaming/generation time
    const tokenCount = response.split(' ').length; // Rough approximation
    const generationTimeMs = (tokenCount / this.config.tokensPerSecond) * 1000;
    await this.delay(generationTimeMs);

    return response;
  }

  private getResponseForPrompt(prompt: string): string {
    if (this.config.preRecordedResponses && this.config.preRecordedResponses[prompt]) {
      return this.config.preRecordedResponses[prompt];
    }
    return `This is a synthetic deterministic response generated by the MockReasoningProvider. ` +
           `It isolates platform overhead for Tier 0 benchmarking.`;
  }

  private delay(ms: number): Promise<void> {
    return new Promise(resolve => setTimeout(resolve, ms));
  }
}
